### ISSUE TITLE
Backup multiple switches on cisco_sg300

### ISSUE THREAD

**Issue by ck-7** [tobor88/PowerShell#1]
how to define multiple switches on this single PowerShell script? and send an email copy of backup config all switches with .zip or rar format using send_mail_message

**Comment by tobor88** [comment]
Hey sorry for the delay I just noticed this. I will take a look at it and get back to you shortly

**Comment by tobor88** [comment]
I have added some sections so you can back up multiple switches that have the same username and password as well as switches that have multiple name and passwords.

Sending zip files through email is usually considered a blocked practice. If you wish to do this any way in an attempt to better protect those files you can add the files to a zip archive using :
```powershell
Compress-Archive -Path $File1,$File2 -DestinationPath $ZipFile
# OR SOMETHING LIKE
Compress-Archive -Path (Get-ChildItem -Path C:\Users\Public\Backups -Recurse -Filter *.txt -ErrorAction SilentlyContinue) -DestinationPath $ZipFile
```

To send an email use : 
```powershell
Send-MailMessage -To $To -From $From -Body $Body -Subject $Subject -UseSSL -Credential (Import-CliXml $CredFile.xml) -Port 587 -SmtpServer smtp-mail.outlook.com
```

If you do not want a credential file saved somewhere the alternative is you can encrypt the password inside the script by using another cmdlet in this repo:
[Hide-PowerShellScriptPassword.ps1](https://github.com/tobor88/PowerShell/blob/master/Hide-PowerShellScriptPassword.ps1)

Once the above Hide-PowerShellScriptPassword cmdlet is run it will automatically generate an AES key saved to a file. You can than hide the password by doing :
```powershell
# Password Encryption
$PasswordFile = "C:\Users\Public\Documents\passwords\<RandomChars>.AESpassword.txt"
$KeyFile = "C:\Users\Public\Documents\keys\<RandomChars>"
$Key = Get-Content -Path $KeyFile
$User = "cisco"

# $Cred can be used with the -Credential Parameter 
$Cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, (Get-Content $PasswordFile | ConvertTo-SecureString -Key $Key)

# $ClearTextPass will need to be used with KiTTY ssh commands. 
$SecurePass = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($cred.Password)
$ClearTextPass = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($SecurePass)
Clear-Variable ClearTextPass, SecurePass, Cred
 ```

**Comment by ck-7** [comment]
@tobor88 Thanks for the reply. I will check and let us know.
This what I  expected.Thanks again

**Comment by tobor88** [comment]
No problem happy to help!
